spring.application.name=LinkHogar
server.port=${PORT:8080}
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true
spring.servlet.encoding.enabled=true
logging.level.org.springframework.security=DEBUG
server.forward-headers-strategy=framework
app.frontend.url=https://linkhogar.com

# Ciclo de vida de docker
spring.docker.compose.lifecycle-management=start_and_stop
spring.docker.compose.stop.command=down
spring.docker.compose.readiness.timeout=2m

#conexion a la base de datos mysql en railway
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Forzamos parametros de compatibilidad
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# JPA / Hibernate (ORM)
#Hibernate solo verificarion que las tablas coinciden con las clases Java. # NO crearan tablas automaticamente. De eso se encargara Flyway.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Flyway (Migraciones)
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Configuracion JWT
jwt.secret=90293YHNYH29O3UR5GBVI23993846T9EGBR098236Y923R3083HB20R847YRFPIWE979238G3UO2BUJBJL230280E2FH2E2IYV23U5CVI235IK23RFD98
jwt.expiration=3600000

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Aumentar limite de subida de archivos (por archivo individual)
spring.servlet.multipart.max-file-size=10MB

# Aumentar limite de subida total (suma de todas las fotos en una misma peticion)
spring.servlet.multipart.max-request-size=50MB
